version: '3.8'

services:
  auth-user-service:
    build:
      context: ./auth-user-service
      dockerfile: Dockerfile
      target: development
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./auth-user-service:/usr/src/app
      - /app/node_modules
    env_file:
      - ./auth-user-service/.env
    profiles:
      - development
    depends_on:
      - mongoose_database
    networks:
      - app-network

  mongoose_database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    profiles:
      - development
      - production
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
